apply plugin: 'maven-publish'

publishing {
    publications {
        release(MavenPublication) {
            groupId 'com.github.hstgis'
            artifactId 'gomaps-sdk-android'
            version '1.1.1'
            artifact('GoMapGLAndroidSDK-1.1.1-release.aar')
            pom {
                packaging = 'aar'
            }
        }
    }
}
